Update for use .env

diff --git a/docker/Dockerfile-php b/docker/Dockerfile-php
--- a/docker/Dockerfile-php
+++ b/docker/Dockerfile-php
@@ -1,23 +1,28 @@
 # Base PHP image
 FROM php:8.3-fpm AS php_base
 
-# Install system dependencies and PHP dependencies
+# Install system dependencies
 RUN set -eux; \
     apt-get update && apt-get upgrade -y && \
     apt-get install -y --no-install-recommends \
-        unzip \
-        git \
-        acl \
-        file \
-        gettext \
-        libicu-dev \
-        libzip-dev \
-    && docker-php-ext-install \
-        intl \
-        pdo \
-        pdo_mysql \
-        zip \
-    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+	acl \
+	file \
+	gettext \
+	git \
+	&& rm -rf /var/lib/apt/lists/*
+
+# Install PHPExtension Manager
+RUN curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
+    -o /usr/local/bin/install-php-extensions && \
+    chmod +x /usr/local/bin/install-php-extensions
+
+# Install PHP Extensions
+RUN set -eux; \
+	install-php-extensions \
+		@composer \
+		intl \
+		zip \
+        pdo_mysql
 
 # Install Composer.
 RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
@@ -31,11 +36,11 @@ RUN curl -sS https://get.symfony.com/cli/installer | bash \
 COPY ./docker/scripts/symfony-start.sh /usr/local/bin/symfony-start.sh
 RUN chmod +x /usr/local/bin/symfony-start.sh
 
-HEALTHCHECK --interval=15s --timeout=10s --start-period=30s --retries=10 CMD [ -f /tmp/healthy ] || exit 1
+#HEALTHCHECK --interval=15s --timeout=10s --start-period=30s --retries=10 CMD [ -f /tmp/healthy ] || exit 1
 ENTRYPOINT ["/usr/local/bin/symfony-start.sh"]
-
+CMD ["sh", "-c", "php-fpm"]
 
 #/*## Execute Entrypoint.
 #
 #
-#CMD ["sh", "-c", "/usr/local/bin/symfony-start.sh && php-fpm"]
+#
